version: '2.1'
services:
  customerloyalty-db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=customerloyaltyuser
      - POSTGRES_PASSWORD=redhat-20
      - POSTGRES_DB=customerloyaltydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - my-network
networks:
  my-network:
    name: todo-network
